export const INFORMACION_PELICULA = "INFORMACION_PELICULA";
export const MOSTRAR_MILISTA = "MOSTRAR_MILISTA";
export const MOSTRAR_CREDITOS = "MOSTRAR_CREDITOS";
export const PELICULAS_LIKE = "PELICULAS_LIKE";
export const LIKES_PELICULAS = "LIKES_PELICULAS";
export const LIKE_REFERENCIA = "LIKE_REFERENCIA";
export const PELI_REFERENCIA = "PELI_REFERENCIA";
export const LOGOUT_LIKE = "LOGOUT_LIKE";

export const MOSTRAR_ALERTA = "MOSTRAR_ALERTA";
export const MOSTRAR_ALERTA_NOMBRE = "MOSTRAR_ALERTA_NOMBRE";
export const MOSTRAR_ALERTA_EMAIL = "MOSTRAR_ALERTA_EMAIL";
export const MOSTRAR_ALERTA_PASSWORD = "MOSTRAR_ALERTA_PASSWORD";
export const MOSTRAR_ALERTA_CONFIRMAR = "MOSTRAR_ALERTA_CONFIRMAR";
export const OCULTAR_ALERTA = "OCULTAR_ALERTA";

export const REGISTRO_EXITOSO = "REGISTRO_EXITOSO";
export const REGISTRO_ERROR = "REGISTRO_ERROR";
export const OBTENER_USUARIO = "OBTENER_USUARIO";
export const LOGIN_EXITOSO = "LOGIN_EXITOSO";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const CERRAR_SESION = "CERRAR_SESION";
